### ISSUE TITLE
allow image manipulation on presigned urls

### ISSUE THREAD

**Issue by nunopato** [nhost/hasura-storage#104]

**Comment by dohomi** [comment]
very much needed - are there any workarounds?

**Comment by dohomi** [comment]
> You can use another image transformation service such as on Cloudflare or Vercel, and send the entire presigned url with signature to their endpoint.
> 
> With Cloudflare you need the pro plan on your domain with image transformation enabled, and make your image src something like `https://images.your.domain/cdn-cgi/image/width=400,fit=cover/{presignedUrl}`

thanks for your reply and succestion. I am using Nhost pro plan and looking for a solution within that scope.

**Comment by dbarrosop** [comment]
this is now supported, if someone wants me to update their cloud version DM me or drop me an email with your subdomain

**Comment by PhilippS93** [comment]
Will this feature also be available in nhost-dart?

**Comment by dbarrosop** [comment]
Awesome, thanks!
