### ISSUE TITLE
Storage.buckets table should be enum 

### ISSUE THREAD

**Issue by spakanati** [nhost/hasura-storage#136]
Similar to nhost/nhost#946 which is about the user roles table, the `storage.buckets` table should be set as enum in Hasura. This would allow for generated types.

**Comment by dbarrosop** [comment]
I don't think this should be an enum. Buckets are dynamic objects that can be created or removed following any logic users desire. While for some users treating buckets as enum may work we can't generalize this as others users may need to manage them dynamically.
