### ISSUE TITLE
Image transformation (quality) does not seem to work properly

### ISSUE THREAD

**Issue by plmercereau** [nhost/hasura-storage#146]
When adding a quality parameter to the query parameters e.g. `?q=5`, the image quality does not change:
- https://ouocgagiibdbglmminql.storage.eu-west-2.nhost.run/v1/files/7e814706-fbf1-4456-9e84-51a57036721e
- https://ouocgagiibdbglmminql.storage.eu-west-2.nhost.run/v1/files/7e814706-fbf1-4456-9e84-51a57036721e?q=5

**Comment by noverby** [comment]
@plmercereau what is the status of this?

**Comment by plmercereau** [comment]
Hi Niclas, no idea; I left Nhost. I guess you can reach out to the team through Discord if this is a blocking point for you. Good luck!

**Comment by dbarrosop** [comment]
PR just opened.
