### ISSUE TITLE
openapi docs: /presignedurl, not /presigned

### ISSUE THREAD

**Issue by outluch** [nhost/hasura-storage#160]
https://github.com/nhost/hasura-storage/blob/5bd777d6c2bdfbdcb31b2a1db29f47d10b39ec5c/controller/openapi.yaml#LL520C5-L520C5

Look, there are `/presigned` in docs, but in reality corrrect url is `/presignedurl`

**Comment by dbarrosop** [comment]
Thanks for reporting, fixed.
