### ISSUE TITLE
Migartions database name should be configurable

### ISSUE THREAD

**Issue by ChrisSG** [nhost/hasura-storage#184]
Currently it seems that the name of the target database for migrations is fixed to "default"

https://github.com/nhost/hasura-storage/blob/97a03dcfce05381fed9f81d9294bb6f2b2197ab7/migrations/hasura.go#L149

This produces the following error when there is no database named "default":

`problem applying hasura metadata: problem adding metadata for the buckets table: status_code: 400\nresponse: {\"error\":\"source with name \\\"default\\\" does not exist\",\"path\":\"$.args\",\"code\":\"not-exists\"}`

Probably it sould be possible to configure it by using an environment variable.

**Comment by dbarrosop** [comment]
That makes sense, feel free to open a PR with the addition.

**Comment by ChrisSG** [comment]
Certainly. PR is here: https://github.com/nhost/hasura-storage/pull/185
