### ISSUE TITLE
Image orientation metadata lost when transformations applied

### ISSUE THREAD

**Issue by wildsurfer** [nhost/hasura-storage#194]
When I'm trying to upload an image that has orientation metadata in EXIF it has a different orientation when I apply any transformations or not.

When I don't apply any transformations it looks as it should (proper orientation taken from EXIF).
Example: https://local.storage.nhost.run/v1/files/967213bb-3f6a-4e31-911d-f7e529867865

But when I apply any transformation orientation is wrong.
Example: https://local.storage.nhost.run/v1/files/967213bb-3f6a-4e31-911d-f7e529867865?q=95&w=375

Here is an example image to play with:
![IMG_3423](https://github.com/nhost/hasura-storage/assets/1456389/081a9cbf-d5b4-4b76-b2a2-b2f22197bc42)

**Comment by wildsurfer** [comment]
And here is how it looks in Nhost dashboard:
<img width="838" alt="Screenshot 2024-01-17 at 14 05 14" src="https://github.com/nhost/hasura-storage/assets/1456389/064a9cb0-f21d-4672-be25-b42873def7a0">

**Comment by dbarrosop** [comment]
0.6.0 should fix this issue, feel free to upgrade and let us know otherwise
