### ISSUE TITLE
Conditinal migration issue

### ISSUE THREAD

**Issue by elitan** [nhost/hasura-storage#57]
Currently, we add a FK to `user.id` from `uploaded_by_user_id` if the `auth.users` table exists. ([link](https://github.com/nhost/hasura-storage/blob/main/migrations/postgres/000001_create-initial-tables.up.sql#L79-L95))

But I think we run into a race condition here.

If Hasura Storage starts before Hsaura Auth the FK will not be created.

At the same time, it seems like Hasura Storage is trying to add a GraphQL Relationship between the columns when its metadata is being applied:

![image](https://user-images.githubusercontent.com/331818/164413543-6ad40ce8-f61a-42ef-9cd2-fc95964d1e2b.png)

Causing Hasura metadata to be out of sync:

![image](https://user-images.githubusercontent.com/331818/164613687-649d4833-1f4f-4fa5-a41d-4fb3453154a2.png)

Either both the migration and the metadata need to be conditional. Or we need to let Storage wait for Auth before it starts and applies its migration and metadata (without conditions).

**Comment by elitan** [comment]
Yea I think we need to decide if we should allow Storage to run independently of Auth

- if yes: We need to conditionally set metadata for `uploadedByUser`
- if no: Storage has to wait for Auth

**Comment by elitan** [comment]
cc @dbarrosop, @nunopato, @plmercereau

**Comment by plmercereau** [comment]
From what I gather, the idea behind splitting HBP into hasura-auth and hasura-storage was to make them independent from each other.
we could also add a  "wait-for" hasura-auth in the hasura-storage k8s deployment resource without changing the hasura-storage code

**Comment by elitan** [comment]
Storage also has to wait for Auth in our CLI in that case.

**Comment by elitan** [comment]
How about we make Storage waiting for Auth the default behavior. And then we can let people opt-in to using the two services independently. How does that sound?

**Comment by elitan** [comment]
After internal discussions we're planning on:

1. Never add an FK between files and users table.
2. Not add a Hasura metadata relationship between the two columns

Users can manually add the Hasura metadata relationship between the two columns if they want to. It won't affect Auth or Storage.

**Comment by elitan** [comment]
Fixed here: https://github.com/nhost/hasura-storage/pull/59
