### ISSUE TITLE
Unable to delete file with storage.delete() using authorization header

### ISSUE THREAD

**Issue by eekrain** [nhost/hasura-storage#81]
I am trying to delete file using storage.delete() from nhost-js package. I am noticing that i couldn't delete file with fileId i wanted to delete, with error 403 "you are not authorized", even with Authorization header with access token in it. So i am trying DELETE method with http client with the url "http://localhost:1337/v1/storage/files/fileId", and im still getting 403 error. But then i tried using x-hasura-admin-secret header and i succesfully deleted the file.

GET file with authorization header: 

![GET file with authorization header](https://user-images.githubusercontent.com/65037854/169659876-540f3604-644e-4cf0-bcaf-034be64204fc.png)

DELETE file using authorization header:

![DELETE file using authorization header](https://user-images.githubusercontent.com/65037854/169659903-5f0f6203-3546-41bd-8206-f7271757fc87.png)

DELETE with x-hasura-admin-secret header: 

![DELETE with x-hasura-admin-secret header](https://user-images.githubusercontent.com/65037854/169659914-c45accca-f00a-470f-be37-a4824b6f2be8.png)

Permission on files table, this access token has administrator role:

![Permission](https://user-images.githubusercontent.com/65037854/169660003-296618da-bfb4-4012-9827-a0f871cac615.png)

Nhost CLI im using : latest v0.6.10

**Comment by eekrain** [comment]
Yo, sorry for late reply. This is my decoded jwt that i got from nhost.auth.getAccessToken():

`{
  "header":{
    "alg":"HS256"
  },
  "payload":{
    "https://hasura.io/jwt/claims":{
      "x-hasura-allowed-roles":[
        "user",
        "me",
        "administrator"
      ],
      "x-hasura-default-role":"administrator",
      "x-hasura-user-id":"0e09fe10-7d69-48ba-90be-771fa569e52d",
      "x-hasura-user-is-anonymous":"false"
    },
    "sub":"0e09fe10-7d69-48ba-90be-771fa569e52d",
    "iss":"hasura-auth",
    "iat":1654191822,
    "exp":1654192722
  }
}`

As you can see, on the allowed roles this token belongs to administrator role, i even made it as the default role.

And then here is the logs from hasura graphql engine :
{"type":"http-log","timestamp":"2022-06-02T17:54:37.120+0000","level":"error","detail":{"operation":{"user_vars":{"x-hasura-role":"administrator","x-hasura-user-is-anonymous":"false","x-hasura-user-id":"0e09fe10-7d69-48ba-90be-771fa569e52d"},"error":{"path":"$.selectionSet.deleteFile.selectionSet.bucket","error":"field \"bucket\" not found in type: 'files'","code":"validation-failed"},"request_id":"0f665d3b-d481-4d77-9a29-4daad744647d","response_size":137,"query":{"variables":{"id":"87d394e0-8446-477f-8837-8b8696d3a065"},"query":"mutation ($id:uuid!){deleteFile(id: $id){id,name,size,bucketId,etag,createdAt,updatedAt,isUploaded,mimeType,uploadedByUserId,bucket{id,minUploadFileSize,maxUploadFileSize,presignedUrlsEnabled,downloadExpiration,createdAt,updatedAt,cacheControl}}}"},"request_mode":"error"},"request_id":"0f665d3b-d481-4d77-9a29-4daad744647d","http_info":{"status":200,"http_version":"HTTP/1.1","url":"/v1/graphql","ip":"127.0.0.1","method":"POST","content_encoding":null}}}

So the error was it failed when requesting bucket table, and im only giving permission on delete in storage.bucket table. Here is the permission on bucket:

![bucket permission](https://user-images.githubusercontent.com/65037854/171696583-9fb42a8b-4158-4ad4-8af6-a8b245d4ee9e.png)

After i gave the administrator role on select permission, it succeeded when deleting the file. I dont know the select permission on bucket table is needed when u want to delete some file, it's not in the docs, please put it in the docs. Thanks for the help, i think u can close this issue.

**Comment by dbarrosop** [comment]
Ok, that issue was fixed and released. Can you try with `0.2.1`? If you are using our cloud service you should have it already, similarly, if you are using our latest cli, you should have it as well (unless you are overriding the version).

**Comment by dbarrosop** [comment]
I am closing this one, if this is still an issue don't hesitate to reopen
