### ISSUE TITLE
File transformation not working properly and in some cases, crashes nhost project temporarily.

### ISSUE THREAD

**Issue by CovenantChurch** [nhost/hasura-storage#82]
I have a ton of image transformations for files I have in my nhost app and they have always kept their aspect ratio in the transformation. However, now they are not. If my request ends with '...?w=400', I get a 1:1 aspect ratio image instead of the aspect ratio of the stored file. In some cases where I'm wanting a thumbnail and I have something along the lines of '...?q=75&w=50', the image doesn't load at all, even though it did before this change occurred.

Update: I also just found out that if you add a height value (?h=500), it returns an error with "an internal server error occurred". If it also has a width, it won't error though.
If I just add a quality transformation to a file, it will make my hasura dashboard go 503 for a few minutes.

Here is a file you can test this on from my project storage: [Test Image](https://svznrpbyjssmrqclkvkg.nhost.run/v1/storage/files/6457132f-d517-419b-a840-77dc89a41165)

**Comment by dbarrosop** [comment]
This has been released, I did some quick tests with your sample image and everything seemed to work fine. I am closing the ticket but if you notice anything strange don't hesitate to reopen and/or comment.

Thanks!
