### ISSUE TITLE
Support for additional storage providers

### ISSUE THREAD

**Issue by azlekov** [nhost/hasura-storage#96]
It would be great if hasura-storage provides support for different storage providers.

A library can be used to add these additional providers or an approach can be taken for a pluggable or extensible storage providing the current one implementation for S3, minio, wasabi and one for gcloud and firebase. 

This `go` library https://gocloud.dev/howto/blob/#services for example supports:
 - Google Cloud (will work if you are using Firebase also)
 - S3
 - Azure Blob storage

**Comment by dbarrosop** [comment]
The storage is designed to allow adding additional storage providers, they just need to implement the `ContentStorage` interface: https://github.com/nhost/hasura-storage/blob/main/controller/controller.go#L68-L77

Looking at the library you linked it seems that it may simplify some bits but you may still need some service-specific code. In any case, it might be a good idea evaluating adding a provider with this library in addition to the one we have right now. If this is something you are interested in doing let me know, I will be happy to help.
